# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20181007_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='insta.Image'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='who_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
