# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20181009_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['posted_on']},
        ),
        migrations.AddField(
            model_name='image',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
