# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20181010_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='posted_on',
        ),
    ]
